import mock from './mock'
import './cards'
import './table'
import './auth/jwt'
import './pages/faq'
import './apps/userList'
import './pages/profile'
import './iconify-icons'
import './apps/permissions'
import './apps/parentMenu'
import './apps/childMenu'
import './master/company'
import './master/client'
import './master/category'
import './master/paymentType'
import './master/accountGroup'
import './master/accountType'
import './transaction/paymentTransaction'
import './transaction/receiptTransaction'
import './transaction/transfer'
import './pages/help-center'
import './server-side-menu/vertical'
import './server-side-menu/horizontal'

mock.onAny().passThrough()
